### ISSUE TITLE
documentation for parsing interfaces on FreeBSD

### ISSUE THREAD

**Issue by afeiszli** [WireGuard/wgctrl-go#114] opened 2021-11-10 17:29 UTC
Hi there, wgctrl has been working great on all device types, except for freebsd. I think it is probably not implemented yet looking at the code, but just looking to see if I'm missing something. wgctrl.New() on freebsd will return no devices, and when you attempt to parse peers, you get "failed to parse interface" (since there's no device I'm guessing).

I would assume it's pretty simple to parse peers using one of the other types if freebsd is not yet supported. Is that a possibility, maybe I'm just setting it up wrong?

**Comment by mdlayher** [comment] 2021-11-10 18:45
Duplicate of #91.

**Closed by mdlayher** 2021-11-10 18:45 UTC
